alter table TRANSSOCCERLEAGUE_FIXTURE add constraint FK_TRANSSOCCERLEAGUE_FIXTURE_ON_TEAM1 foreign key (TEAM1_ID) references TRANSSOCCERLEAGUE_TEAM(ID);
alter table TRANSSOCCERLEAGUE_FIXTURE add constraint FK_TRANSSOCCERLEAGUE_FIXTURE_ON_TEAM2 foreign key (TEAM2_ID) references TRANSSOCCERLEAGUE_TEAM(ID);
create index IDX_TRANSSOCCERLEAGUE_FIXTURE_ON_TEAM1 on TRANSSOCCERLEAGUE_FIXTURE (TEAM1_ID);
create index IDX_TRANSSOCCERLEAGUE_FIXTURE_ON_TEAM2 on TRANSSOCCERLEAGUE_FIXTURE (TEAM2_ID);
